### ISSUE TITLE
Hello! 

### ISSUE THREAD

**Issue by makhfib** [jawad846/terraform_script#1]
We are a team building a startup and we found ourselves digging into your post on [EC2 Auto Scaling](https://medium.com/tensult/amazon-ec2-auto-scaling-884ea50d2d). We are struggeling to make an estimate of how much our costs could grow with the increase of our monthly active users.

We'd love to have you guide us a little bit, as we've seen you are pretty well trained in AWS!

Please, add me on LinkedIn "Mohammed Makhfi Boulaich".

Thank you very much and sorry for opening an issue. I couldn't find another way to contact you.

Best regards,
Mohammed

**Comment by jawad846** [comment]
where did you find the error in the autoscaling code
